import React, { useEffect, useLayoutEffect, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import Lenis from 'lenis';
import './style.css';
import './assets.css';

gsap.registerPlugin(ScrollTrigger);
const projects = [
  ['01', 'GL ULTRA CLEAN', 'Next.js / React / TypeScript / Tailwind CSS', 'violet', 'https://github.com/markoswcs/GL-ULTRA-CLEAN', '/assets/project-gl-ultra-mockup.png'],
  ['02', 'SFL PRO', 'JavaScript / Capacitor / Supabase / PWA', 'acid', 'https://github.com/markoswcs/SuperSFL', '/assets/project-sfl-mockup.png'],
  ['03', 'NOTION TEMPLATES', 'HTML / CSS / JavaScript', 'violet', 'https://github.com/markoswcs/notion-templates', '/assets/project-notion.png']
];
const services = ['DESENVOLVIMENTO WEB', 'APLICAÇÕES MOBILE', 'IA E PROMPTS', 'UX E DESIGN', 'ESTRATÉGIA DIGITAL'];

function Header(){ return <header><span>MARKOS WINYCIUS®</span><nav><a href="#about">SOBRE</a><a href="#projects">PROJETOS</a><a href="#contact">CONTATO</a></nav><span>BRASÍLIA, DF</span></header> }
function Hero(){const move=e=>{const b=e.currentTarget.getBoundingClientRect(),x=(e.clientX-b.left)/b.width-.5,y=(e.clientY-b.top)/b.height-.5;e.currentTarget.style.setProperty('--head-x',`${x*145}px`);e.currentTarget.style.setProperty('--head-y',`${y*34}px`);e.currentTarget.style.setProperty('--title-x',`${x*-12}px`);e.currentTarget.style.setProperty('--copy-x',`${x*-18}px`);e.currentTarget.style.setProperty('--pill-x',`${x*-22}px`)};const reset=e=>['--head-x','--head-y','--title-x','--copy-x','--pill-x'].forEach(v=>e.currentTarget.style.setProperty(v,'0px'));return <section className="hero" onPointerMove={move} onPointerLeave={reset}><Header/><img className="hero-head markos-portrait" src="/assets/markos-portrait.png" alt="Retrato de Markos Winycius"/><div className="hero-title">OI, SOU O MARKOS</div><p className="hero-copy"><strong>Engenheiro de Software</strong> que manja usar IA<br/>para sites, imagens e talvez (quase tudo)<br/>que você precisar.</p><a className="pill hero-pill" href="#projects">VEJA OS PROJETOS <b>↘</b></a><div className="scroll-note">001 — PORTFÓLIO 2026</div></section> }
function Gallery(){const section=useRef();useEffect(()=>{const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){section.current.classList.add('is-visible');observer.disconnect()}},{threshold:.22});observer.observe(section.current);return()=>observer.disconnect()},[]);return <section ref={section} className="creative"><div className="creative-label">02 — CRIATIVIDADE APLICADA</div><div className="creative-copy"><h2>CRIATIVIDADE<br/><em>EM CODIGO<span className="creative-period">.</span></em></h2><p>Não é só sobre escrever código. É sobre conectar tecnologia, IA e design para transformar uma ideia em uma experiência que funciona.</p><span>IA GENERATIVA · WEB · MOBILE · DESIGN</span></div><div className="creative-brain"><img src="/assets/creative-brain.png" alt="Cérebro 3D representando criatividade e tecnologia"/></div><div className="creative-note">PENSAR · CRIAR · CONSTRUIR</div></section>}
function About(){const section=useRef();useEffect(()=>{const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){section.current.classList.add('is-visible');observer.disconnect()}},{threshold:.18});observer.observe(section.current);return()=>observer.disconnect()},[]);const move=e=>{const b=e.currentTarget.getBoundingClientRect(),x=(e.clientX-b.left)/b.width-.5,y=(e.clientY-b.top)/b.height-.5;e.currentTarget.style.setProperty('--about-x',`${x*36}px`);e.currentTarget.style.setProperty('--about-y',`${y*22}px`)};const reset=e=>{e.currentTarget.style.setProperty('--about-x','0px');e.currentTarget.style.setProperty('--about-y','0px')};return <section ref={section} id="about" className="about about-markos" onPointerMove={move} onPointerLeave={reset}><div className="about-grid"></div><div className="cosmos black-hole"><i></i><b></b></div><div className="cosmos star star-one">✦</div><div className="cosmos star star-two">✧</div><h2>SOBRE MIM</h2><div className="about-profile"><div className="about-orbit orbit-one"><span>IA</span><span>WEB</span></div><div className="about-orbit orbit-two"><span>UX</span><span>CODE</span></div><img src="/assets/markos-portrait.png" alt="Caricatura de Markos Winycius"/></div><article className="about-data data-left"><small>QUEM SOU</small><strong>MARKOS WINYCIUS</strong><p>Formado em Engenharia de Software.</p><span>UNICEPLAC · TURMA 2026</span></article><article className="about-data data-right"><small>ONDE EU ENTREGO</small><strong>TECNOLOGIA<br/>COM PROPÓSITO.</strong><p>Web, mobile, IA generativa, UX e estratégia digital.</p><span>REACT · NEXT.JS · TYPESCRIPT</span></article><article className="about-data data-creative"><small>IDEIAS EM ÓRBITA</small><strong>CRIATIVIDADE<br/>SEM LIMITES.</strong><p>Transformo referências, problemas e ideias em caminhos visuais e digitais.</p><span>IMAGINAR · CONECTAR · CRIAR</span></article><article className="about-data data-execution"><small>MISSÃO CUMPRIDA</small><strong>EXECUÇÃO<br/>QUE ENTREGA.</strong><p>Do conceito ao produto: foco, ritmo e acabamento em cada detalhe.</p><span>ESTRATÉGIA · CÓDIGO · IMPACTO</span></article><div className="about-copy"><p>Transformo ideias em produtos digitais com código, IA e uma curiosidade que não para quieta.</p><a className="pill light" href="https://wa.me/5561999963686" target="_blank" rel="noreferrer">FALAR NO WHATSAPP ↗</a></div></section> }
function Services(){ return <section className="services panel"><h2>COMPET&Ecirc;NCIAS</h2><div className="service-list">{services.map((s,i)=><article key={s}><strong>0{i+1}</strong><h3>{s}</h3><p>{['React, Next.js, TypeScript, HTML, CSS e JavaScript.','Capacitor, Supabase, PWA e integrações com WhatsApp.','Uso avançado para criação de sites, sistemas, imagens e conteúdo.','Figma e Photoshop em nível intermediário, com foco em usabilidade.','Atendimento, crescimento, marketing e gestão de clientes.'][i]}</p><div className="service-scene" aria-hidden="true"><i></i><b></b><em></em></div></article>)}</div></section> }
function ProjectCard({project,index}){return <article className="project" style={{'--offset':`${20+index*64}px`,zIndex:10+index}}><div className="project-head"><b>{project[0]}</b><strong>{project[1]}</strong><span>{project[2]}</span><a className="pill" href={project[4]} target="_blank" rel="noreferrer">VER PROJETO ↗</a></div><div className={`project-art ${project[3]}`}><figure className="project-screen" style={{'--project-image':`url(${project[5]})`}}><img src={project[5]} alt={`Tela do projeto ${project[1]}`}/><figcaption>DESTAQUE DO PROJETO</figcaption></figure></div></article>}
function Projects(){return <section id="projects" className="projects panel"><h2>PROJETOS</h2><div className="project-stack">{projects.map((p,i)=><ProjectCard key={p[0]} project={p} index={i}/>)}</div></section>}
function Testimonials(){const section=useRef();useEffect(()=>{const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){section.current.classList.add('is-visible');observer.disconnect()}},{threshold:.16});observer.observe(section.current);return()=>observer.disconnect()},[]);const items=[['01','FORMAÇÃO ACADÊMICA','ENGENHARIA DE SOFTWARE','Bacharelado em Engenharia de Software — UNICEPLAC. 2023 a 2026, 8º semestre.',['UNICEPLAC','2023 — 2026']],['02','DESIGN & NEGÓCIOS','CRIATIVIDADE APLICADA','FigFlow: Design gráfico no Figma. Fundação Bradesco: Administração, Empreendedorismo e Inovação.',['FIGMA','INOVAÇÃO']],['03','SEGURANÇA & DADOS','BASES DIGITAIS','UNIEDUCAR: LGPD, Segurança da Informação, Auditoria de Sistemas e Tecnologias na Educação Digital.',['LGPD','SEGURANÇA']],['04','EM EVOLUÇÃO','APRENDIZADO CONTÍNUO','Estudo constante de IA, desenvolvimento web, experiência do usuário e novas tecnologias.',['IA','WEB','UX']]];return <section ref={section} className="testimonials"><div className="cert-kicker">03 — CONHECIMENTO EM MOVIMENTO</div><h2>FORMAÇÃO E<br/>CERTIFICAÇÕES</h2><div className="quotes">{items.map(([number,label,title,text,tags])=><article key={number}><div className="quote-top"><span>✦</span><b>{number}</b></div><small>{label}</small><h3>{title}</h3><p>{text}</p><div className="quote-tags">{tags.map(tag=><i key={tag}>{tag}</i>)}</div></article>)}</div></section>}
function Contact(){return <><section id="contact" className="contact panel"><div className="contact-orb"><i></i><b></b></div><div className="contact-star">✳</div><small className="contact-kicker">04 — PRÓXIMA IDEIA</small><h2>VAMOS<br/>CONVERSAR</h2><p className="contact-intro">Tem uma ideia, desafio ou produto para tirar do papel? Vamos construir algo que faça diferença.</p><div className="contact-actions"><a className="contact-mail" href="mailto:mw64097@gmail.com">MW64097@GMAIL.COM ↗</a><a className="contact-whatsapp" href="https://wa.me/5561999963686" target="_blank" rel="noreferrer">CHAMAR NO WHATSAPP ↗</a></div><nav className="contact-socials" aria-label="Redes sociais"><a href="https://www.linkedin.com/in/markos-winycius-cavalcante-santos-7786933b8/" target="_blank" rel="noreferrer">LINKEDIN <b>↗</b></a><a href="https://github.com/markoswcs" target="_blank" rel="noreferrer">GITHUB <b>↗</b></a><a href="https://www.instagram.com/markoswcs/?hl=pt-br" target="_blank" rel="noreferrer">INSTAGRAM <b>↗</b></a></nav></section><footer><small className="footer-kicker">MARKOS WINYCIUS — PORTFÓLIO 2026</small><div>MARKOS<br/>WINYCIUS</div><aside className="footer-galaxy" aria-hidden="true"><i></i><b></b><em></em></aside><a className="footer-cta" href="#contact">VAMOS CRIAR ALGO JUNTOS <b>↗</b></a><span><a href="https://www.instagram.com/markoswcs/?hl=pt-br" target="_blank" rel="noreferrer">INSTAGRAM</a><a href="https://www.linkedin.com/in/markos-winycius-cavalcante-santos-7786933b8/" target="_blank" rel="noreferrer">LINKEDIN</a><a href="https://github.com/markoswcs" target="_blank" rel="noreferrer">GITHUB</a></span></footer></>}
function App(){const root=useRef();useLayoutEffect(()=>{const lenis=new Lenis({lerp:.09});let raf=t=>{lenis.raf(t);requestAnimationFrame(raf)};requestAnimationFrame(raf);const ctx=gsap.context(()=>{gsap.set('.hero-head',{xPercent:-50});gsap.timeline().fromTo('.hero-title',{opacity:0,clipPath:'inset(0 0 100% 0)'},{opacity:1,clipPath:'inset(0 0 0% 0)',duration:1.05,ease:'power4.out',delay:.15}).fromTo('.markos-portrait',{opacity:0},{opacity:1,duration:.8,ease:'power2.out'},'-=.55').fromTo('.hero-copy,.hero-pill,.scroll-note',{opacity:0,y:16},{opacity:1,y:0,duration:.55,stagger:.09,ease:'power2.out'},'-=.25');gsap.to('.hero > :not(.hero-head)',{y:-170,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:true}});gsap.to('.hero-head',{y:-260,rotate:8,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:true}});const creativeTimeline=gsap.timeline({scrollTrigger:{trigger:'.creative',start:'top 88%',end:'top 26%',scrub:1}});creativeTimeline.fromTo('.creative-label',{opacity:0,x:-44},{opacity:1,x:0,ease:'power3.out'},0).fromTo('.creative-copy h2',{opacity:0,y:120,clipPath:'inset(0 0 100% 0)'},{opacity:1,y:0,clipPath:'inset(0 0 0% 0)',ease:'power4.out'},.08).fromTo('.creative-copy p,.creative-copy span',{opacity:0,y:32},{opacity:1,y:0,stagger:.08,ease:'power2.out'},.28).fromTo('.creative-brain',{opacity:0,scale:.42,rotate:-26,x:220},{opacity:1,scale:1,rotate:0,x:0,ease:'power4.out'},.02).fromTo('.creative-note',{opacity:0,y:45},{opacity:1,y:0,ease:'power2.out'},.32).to('.creative',{'--creative-glow':1,ease:'power2.out'},0);gsap.to('.about h2',{color:'#f4f4f4',webkitTextStroke:'0px',scrollTrigger:{trigger:'.about',start:'top 80%',end:'top 35%',scrub:true}});gsap.utils.toArray('.orb').forEach((el,i)=>gsap.from(el,{opacity:0,scale:.6,rotate:-25+i*15,scrollTrigger:{trigger:'.about',start:'top 70%',end:'top 35%',scrub:true}}));gsap.utils.toArray('.service-list article').forEach((row,i)=>{const title=row.querySelector('h3'),text=row.querySelector('p'),number=row.querySelector('strong');const trigger={trigger:row,start:'top 92%',end:'top 43%',scrub:true};gsap.fromTo(row,{clipPath:'inset(0 100% 0 0)',scale:.88,'--service-glow':0},{clipPath:'inset(0 0% 0 0)',scale:1,'--service-glow':1,ease:'none',scrollTrigger:trigger});gsap.fromTo(title,{xPercent:-25,letterSpacing:'-.14em'},{xPercent:0,letterSpacing:'-.06em',ease:'none',scrollTrigger:{...trigger}});gsap.fromTo([number,text],{x:55,opacity:0},{x:0,opacity:1,ease:'none',scrollTrigger:{...trigger}});});},root);return()=>{ctx.revert();lenis.destroy()}},[]);return <main ref={root}><Hero/><Gallery/><About/><Services/><Projects/><Testimonials/><Contact/></main>};
function App2(){
  const root=useRef();
  useEffect(()=>{const sections=document.querySelectorAll('.services,.projects,.testimonials,.contact,footer');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>entry.target.classList.toggle('scroll-active',entry.isIntersecting)),{threshold:.18});sections.forEach(section=>observer.observe(section));return()=>observer.disconnect()},[]);
  useLayoutEffect(()=>{
    const lenis=new Lenis({lerp:.09});
    const raf=t=>{lenis.raf(t);requestAnimationFrame(raf)};
    requestAnimationFrame(raf);
    const ctx=gsap.context(()=>{
      gsap.set('.hero-head',{xPercent:-50});
      gsap.timeline().fromTo('.hero-title',{opacity:0,clipPath:'inset(0 0 100% 0)'},{opacity:1,clipPath:'inset(0 0 0% 0)',duration:1.05,ease:'power4.out',delay:.15}).fromTo('.markos-portrait',{opacity:0},{opacity:1,duration:.8,ease:'power2.out'},'-=.55').fromTo('.hero-copy,.hero-pill,.scroll-note',{opacity:0,y:16},{opacity:1,y:0,duration:.55,stagger:.09,ease:'power2.out'},'-=.25');
      gsap.to('.hero > :not(.hero-head)',{y:-170,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:true}});
      gsap.to('.hero-head',{y:-260,rotate:8,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:true}});
      const creativeTimeline=gsap.timeline({scrollTrigger:{trigger:'.creative',start:'top 75%',toggleActions:'play none none reverse'}});
      creativeTimeline.fromTo('.creative-label',{opacity:0,x:-44},{opacity:1,x:0,duration:.45,ease:'power3.out'},0).fromTo('.creative-copy h2',{opacity:0,y:120,clipPath:'inset(0 0 100% 0)'},{opacity:1,y:0,clipPath:'inset(0 0 0% 0)',duration:.9,ease:'power4.out'},.1).fromTo('.creative-copy p,.creative-copy span',{opacity:0,y:32},{opacity:1,y:0,duration:.45,stagger:.1,ease:'power2.out'},.55).fromTo('.creative-brain',{opacity:0,scale:.42,rotate:-26,x:220},{opacity:1,scale:1,rotate:0,x:0,duration:1.15,ease:'back.out(1.35)'},.03).fromTo('.creative-note',{opacity:0,y:45},{opacity:1,y:0,duration:.4,ease:'power2.out'},.68).to('.creative',{'--creative-glow':1,duration:.9,ease:'power2.out'},0);
      gsap.to('.about h2',{color:'#f4f4f4',webkitTextStroke:'0px',scrollTrigger:{trigger:'.about',start:'top 80%',end:'top 35%',scrub:true}});
      gsap.utils.toArray('.orb').forEach((el,i)=>gsap.from(el,{opacity:0,scale:.6,rotate:-25+i*15,scrollTrigger:{trigger:'.about',start:'top 70%',end:'top 35%',scrub:true}}));
      gsap.utils.toArray('.service-list article').forEach((row,i)=>{const title=row.querySelector('h3'),text=row.querySelector('p'),number=row.querySelector('strong'),trigger={trigger:row,start:'top 92%',end:'top 43%',scrub:true};gsap.fromTo(row,{clipPath:'inset(0 100% 0 0)',scale:.88,'--service-glow':0},{clipPath:'inset(0 0% 0 0)',scale:1,'--service-glow':1,ease:'none',scrollTrigger:trigger});gsap.fromTo(title,{xPercent:-25,letterSpacing:'-.14em'},{xPercent:0,letterSpacing:'-.06em',ease:'none',scrollTrigger:{...trigger}});gsap.fromTo([number,text],{x:55,opacity:0},{x:0,opacity:1,ease:'none',scrollTrigger:{...trigger}});});
    },root);
    return()=>{ctx.revert();lenis.destroy()};
  },[]);
  return <main ref={root}><Hero/><Gallery/><About/><Services/><Projects/><Testimonials/><Contact/></main>;
}

createRoot(document.getElementById('root')).render(<App2/>);
